### ISSUE TITLE
send-to-user command fails because mismatched arguments

### ISSUE THREAD

**Issue by RaederDev** [humhub/fcm-push#22]
In this class only 5 out of 6 required arguments are passed, resulting in an exception being thrown:
https://github.com/humhub/fcm-push/blob/master/commands/SendController.php#L20
  
Adding "null" as an additional argument solves the issue.

**Comment by luke-** [comment]
Fixed here: https://github.com/humhub/fcm-push/commit/79703a3d45b10c36785a8abe85a93e51a9cdc0f9
