### ISSUE TITLE
Create Endpoint to Test Push Status

### ISSUE THREAD

**Issue by luke-** [humhub/fcm-push#37]
We need an endpoint for the mobile app, e.g. `/fcm-push/mobile-app/status` to display a warning if necessary.

- 200: OK, Push (Proxy) is correctly configured
- 404: FCM Module is not installed
- 501: Push Proxy is not configured

Related: https://github.com/humhub/app/issues/98

**Comment by yurabakhtin** [comment]
@luke- Done in the PR https://github.com/humhub/fcm-push/pull/38.
