### ISSUE TITLE
The "See online" links in the email summary does not use the "go.humhub.com" service

### ISSUE THREAD

**Issue by marc-farre** [humhub/fcm-push#41]
These links:
![image](https://github.com/humhub/fcm-push/assets/23310825/999eee43-a345-4de0-ad5e-84801936d5b7)

should start with https://go.humhub.com/?url=xxxxx

Causes https://github.com/humhub/app/issues/194 app issue

**Comment by yurabakhtin** [comment]
@luke- @marc-farre Fixed in the PR https://github.com/humhub/fcm-push/pull/42.
The problem was in the multiline link [here](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/activity/views/layouts/mail.php#L101-L103).
